// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module townesquare_sc::post_updated {

    use std::string::String;
    use townesquare_sc::post::{Self, PostUpdated};

    public fun post_id(post_updated: &PostUpdated): u128 {
        post::post_updated_post_id(post_updated)
    }

    public fun poster(post_updated: &PostUpdated): address {
        post::post_updated_poster(post_updated)
    }

    public fun user_id(post_updated: &PostUpdated): String {
        post::post_updated_user_id(post_updated)
    }

    public fun content(post_updated: &PostUpdated): String {
        post::post_updated_content(post_updated)
    }

    public fun digest(post_updated: &PostUpdated): String {
        post::post_updated_digest(post_updated)
    }

}
