// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module townesquare_sc::post_created {

    use std::string::String;
    use townesquare_sc::post::{Self, PostCreated};

    public fun post_id(post_created: &PostCreated): u128 {
        post::post_created_post_id(post_created)
    }

    public fun poster(post_created: &PostCreated): address {
        post::post_created_poster(post_created)
    }

    public fun user_id(post_created: &PostCreated): String {
        post::post_created_user_id(post_created)
    }

    public fun content(post_created: &PostCreated): String {
        post::post_created_content(post_created)
    }

    public fun digest(post_created: &PostCreated): String {
        post::post_created_digest(post_created)
    }

}
