// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module townesquare_sc::post_deleted {

    use townesquare_sc::post::{Self, PostDeleted};

    public fun post_id(post_deleted: &PostDeleted): u128 {
        post::post_deleted_post_id(post_deleted)
    }

}
