// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module townesquare_sc::user_deleted {

    use townesquare_sc::user::{Self, UserDeleted};

    public fun user_wallet(user_deleted: &UserDeleted): address {
        user::user_deleted_user_wallet(user_deleted)
    }

}
